services:
  - type: web
    name: partner-classification
    env: python
    buildCommand: pip install -r requirements.txt && python -m playwright install
    startCommand: gunicorn app:app --workers 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8000
      - key: OPENAI_API_KEY
        sync: false
        fromVariable: OPENAI_API_KEY
      - key: ANTHROPIC_API_KEY
        sync: false 